spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456


mybatis:
  configuration:
#    开启驼峰命名与数据库字段的映射
    map-underscore-to-camel-case: true